server:
  port: 9000


eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: hystrix-consumer # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true

# 设置Ribbon的超时时间
ribbon:
  ConnectTimeout: 1000 # 网络连接超时时间
  ReadTimeout: 5000 # 服务提供方处理时间过长时，要在此处改动逻辑处理的超时时长
