server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: business-gateway

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合
      # id: 唯一标识。默认是一个UUID
      # uri: 转发路径
      # predicates: 条件,用于请求网关路径的匹配规则

      - id: gateway-seller
        uri: lb://business-seller
        predicates:
        - Path=/seller/**

      - id: gateway-goods
        uri: lb://business-goods
        predicates:
        - Path=/goods/**

      # 微服务名称配置
      discovery:
        locator:
          enabled: true # 设置为true 请求路径前可以添加微服务名称
          lower-case-service-id: true # 允许为小写
