server:
  port: 9000

eureka:

  instance:
    # 主机名
    hostname: localhost

  client:
    service-url:
      # eureka服务端地址，将来客户端使用该地址和
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径
    name: eureka-consumer