server:
  port: 80


# 设置eureka的服务路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway-server

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则  集合
      routes:
      # id: 唯一标识。默认是一个UUID
      # uri: 转发路径
      # predicates: 条件,用于请求网关路径的匹配规则
      # filters：配置局部过滤器的
      - id: gateway-provider
        # uri: http://localhost:8000/   # 静态路由
        uri: lb://gateway-provider       # 动态路由
        predicates:
        - Path=/goods/**
        filters:
        - AddRequestParameter=username,zhangsan

      - id: gateway-consumer
        # uri: http://localhost:9000/   # 静态路由
        uri: lb://gateway-consumer       # 动态路由
        predicates:
        - Path=/order/**

      # 微服务名称配置
      discovery:
        locator:
          # 设置为true 请求路径前可以添加微服务名称
          enabled: true
          lower-case-service-id: true # 允许为小写
