server:
  port: 80


# 设置eureka的服务路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway-server

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则  集合
      routes:
      # id: 唯一标识。默认是一个UUID
      # uri: 转发路径
      # predicates: 条件,用于请求网关路径的匹配规则
      - id: gateway-provider
        # uri: http://localhost:8000/   # 静态路由
        uri: lb://gateway-provider       # 动态路由
        predicates:
          - Path=/goods/**

      - id: gateway-consumer
        # uri: http://localhost:9000/   # 静态路由
        uri: lb://gateway-consumer       # 动态路由
        predicates:
          - Path=/order/**
